# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BingLi',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('SongJianRiQi', models.DateTimeField(verbose_name='\u9001\u68c0\u65e5\u671f')),
                ('XingMing', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('NianLing', models.IntegerField(verbose_name='\u5e74\u9f84')),
                ('XingBie', models.CharField(max_length=10, verbose_name='\u6027\u522b')),
                ('BuMen', models.CharField(max_length=100, verbose_name='\u90e8\u95e8')),
                ('LinChuangZhenDuan', models.CharField(max_length=1000, verbose_name='\u4e34\u5e8a\u8bca\u65ad')),
                ('QuCaiBuWei', models.CharField(max_length=100, verbose_name='\u53d6\u6750\u90e8\u4f4d')),
                ('SongJianYiShi', models.CharField(max_length=100, verbose_name='\u9001\u68c0\u65e5\u671f')),
                ('BaoGaoYiShi', models.CharField(max_length=100, verbose_name='\u62a5\u544a\u533b\u5e08')),
                ('Operator', models.CharField(max_length=100, verbose_name='\u64cd\u4f5c\u533b\u5e08')),
                ('BingLiHao', models.IntegerField(verbose_name='\u75c5\u5386\u53f7')),
                ('JingXiaSuoJian', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u955c\u4e0b\u6240\u89c1')),
                ('BingLiZhenDuan', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u75c5\u7406\u8bca\u65ad')),
                ('BaoGaoRiQi', models.DateTimeField(blank=True, null=True, verbose_name='\u62a5\u544a\u65e5\u671f')),
                ('ZhuYuanHao', models.IntegerField(blank=True, null=True, verbose_name='\u4f4f\u9662\u53f7')),
            ],
        ),
        migrations.CreateModel(
            name='DigHistoryBasic',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('XianBingShi', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u73b0\u75c5\u53f2')),
                ('JiWangShi', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u65e2\u5f80\u53f2')),
                ('JiaZuShi', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u5bb6\u65cf\u53f2')),
                ('TiGeJianCha', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u4f53\u683c\u68c0\u67e5')),
                ('LinChuangJianCha', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u4e34\u5e8a\u68c0\u67e5')),
                ('ZhiLiao', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u6cbb\u7597')),
                ('Sign', models.CharField(max_length=1000, verbose_name='\u6ce8\u518c\u533b\u5e08')),
                ('PhotoNum', models.IntegerField(blank=True, null=True, verbose_name='\u56fe\u50cf\u6570\u91cf')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=100, verbose_name='\u56fe\u50cf\u8def\u5f84')),
                ('Password', models.CharField(max_length=100, verbose_name='\u56fe\u50cf\u8def\u5f84')),
            ],
        ),
        migrations.CreateModel(
            name='PatientBasicInfo',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('Birthday', models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5')),
                ('Age', models.IntegerField(verbose_name='\u5e74\u9f84')),
                ('Gender', models.IntegerField(verbose_name='\u6027\u522b')),
                ('Marriage', models.IntegerField(blank=True, null=True, verbose_name='\u5a5a\u5426')),
                ('HomeTown', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7c4d\u8d2f')),
                ('Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4f4f\u5740')),
                ('Phone', models.IntegerField(blank=True, null=True, verbose_name='\u7535\u8bdd')),
                ('InputDate', models.DateTimeField(verbose_name='\u8f93\u5165\u65e5\u671f')),
                ('PiFuKeBingLiHao', models.IntegerField(verbose_name='\u76ae\u80a4\u79d1\u75c5\u5386\u53f7')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('PhotoType', models.CharField(max_length=100, verbose_name='\u56fe\u50cf\u7c7b\u578b')),
                ('Photo', models.CharField(max_length=100, verbose_name='\u56fe\u50cf\u8def\u5f84')),
                ('IdentifyID', models.CharField(max_length=100, verbose_name='\u5b9a\u4e49ID')),
                ('Description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u63cf\u8ff0')),
                ('PatientID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zscg.PatientBasicInfo')),
            ],
        ),
        migrations.AddField(
            model_name='dighistorybasic',
            name='PatientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zscg.PatientBasicInfo'),
        ),
        migrations.AddField(
            model_name='bingli',
            name='PatientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zscg.PatientBasicInfo'),
        ),
    ]
